#!/bin/bash

awk '
	/^SwapTotal:/ {
		swap_total=$2
	}
	/^SwapFree:/ {
		swap_free=$2
	}
	/^SwapCached:/ {
		swap_cached=$2
	}
	END {
		swap_used = swap_total - (swap_free + swap_cached)
		percent = swap_used/swap_total*100
		printf("%.2f%\n", percent)
		printf("%.2f%\n", percent)
		if(percent > 66)
			printf("#FA0C0D\n")
		else if(percent > 33)
			printf("#FACC2E\n")
		else
			printf("#00CC00\n")
	}
' /proc/meminfo
